version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: jazzman/wp-app-config
    versions:
    - 2.1.0
  - dependency-name: symfony/var-dumper
    versions:
    - 5.2.2
    - 5.2.4
    - 5.2.5
  - dependency-name: roots/wordpress
    versions:
    - "5.6"
    - 5.6.1
    - "5.7"
  - dependency-name: composer/installers
    versions:
    - 1.10.0
  - dependency-name: jazzman/wp-performance
    versions:
    - 2.0.0
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: sass
    versions:
    - 1.32.11
    - 1.32.5
    - 1.32.6
    - 1.32.7
    - 1.32.8
  - dependency-name: "@wordpress/block-library"
    versions:
    - 2.27.2
    - 2.28.0
    - 2.28.2
    - 2.28.3
    - 2.28.4
    - 2.28.5
    - 2.28.6
    - 2.28.7
    - 2.29.0
    - 2.29.1
  - dependency-name: "@wordpress/base-styles"
    versions:
    - 3.3.1
    - 3.3.2
    - 3.3.3
    - 3.4.0
    - 3.4.1
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: "@types/bootstrap"
    versions:
    - 5.0.5
    - 5.0.7
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.24
    - 14.14.25
    - 14.14.26
    - 14.14.28
    - 14.14.30
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
